### ISSUE TITLE
test_prob- not getting enough positive diagnoses

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#150]
This may be expected, but let's clarify:
Here is test output (test hasn't been merged yet):
> AssertionError: 1278.0 not greater than or equal to 1398.1504717027778 : Expected at least 1398.1504717027778 diagnoses with 1580.0 symptomatic and 0.9 sensitivity. Got 1278.0 diagnoses, which is too low.

Here is the debugging output:
```
        Max: 1445.8495282972222
        Min: 1398.1504717027778
        Target: 1580.0
        Target: 1580.0
        Ideal: 1422.0
        Sensitivity: 0.9
        Actual diagnoses: 1278.0
```

I note that at the same timestep, we have 148 recoveries.  If those are removed from the symptomatic count ('n_symptomatic' is calculated before 'n_recoveries') then I think this accounts for the difference:
1580 symptomatic  -148 recoveries = 1432 persons who might test positive * 0.9 = 1288 or "pretty close to 1278"

**Comment by CWiswell-IDM** [comment]
I could test this to see if this is the problem if I could figure out how in people.test() to add the "people who went into recovered state today" to the list of is_infectious.

**Comment by CWiswell-IDM** [comment]
Okay, I tried rerunning the test and subtracting the recoveries on test day like so:
```
            first_day_diagnoses = self.get_full_result_channel(
                channel=ResultsKeys.diagnoses_at_timestep
            )[start_day + 1]
            symptomatic_today = self.get_full_result_channel(
                channel=ResultsKeys.symptomatic_at_timestep
            )[start_day]
            recoveries_today = self.get_full_result_channel(
                channel=ResultsKeys.recovered_at_timestep
            )[start_day]
            target_count = symptomatic_today - recoveries_today
            ideal_diagnoses = target_count * sensitivity
```.

This worked for the 0.9 sensitivity test, but the 0.7 sensitivity test came in way, way lower than it should have:
```
        Max: 1037.0825604591125
        Min: 967.7174395408874
        Target: 1432.0
        Previous day Target: 1407.0
        Sensitivity: 0.7
        Ideal: 1002.4
        Actual diagnoses: 760.0
``` (Max and Min are the ideal number of tests +- two standard deviations)

I've updated the bug title "not getting enough diagnoses" and I'll continue working on more tests.

**Comment by cliffckerr** [comment]
@CWiswell-IDM thank you for finding this! this was a bug, `test_sensitivity` was copied twice instead of `loss_prob`. Fixed now

**Comment by CWiswell-IDM** [comment]
I still show this happening. Here's the debug log
> Initializing sim with 5000 people for 31 days
        Max: 55.829900661162455
        Min: 46.770099338837554
        Target: 57.0
        Previous day Target: 50.0
        Sensitivity: 0.9
        Ideal: 51.300000000000004
        Actual diagnoses: 44.0

The "Target" is the number of people symptomatic, all of whom should be tested.  The "Ideal" is that number times sensitivity of 0.9.   The Max and Min are +- 2 standard deviations.

I've attached parameters to try.

[DEBUG_test_interventions.InterventionTests.test_test_prob_sensitivity.txt](https://github.com/InstituteforDiseaseModeling/covasim/files/4506581/DEBUG_test_interventions.InterventionTests.test_test_prob_sensitivity.txt)

**Comment by cliffckerr** [comment]
Closed by #171
